### ISSUE TITLE
Application init with No such file or directory

### ISSUE THREAD

**Issue by pmverma** [wimdeblauwe/ttcli#170]
I installed ttcli using brew.

```
➜  ttcli-demo ttcli version  
1.5.1
```
Then `ttcli init` which is resulting 

```
➜  ttcli-demo ttcli init 
? Group:  com.example
? Artifact:  demo
? Project Name:  Demo
? Select Spring Boot version 3.3.4
? Select live reload implementation: dev-tools-based
? Web dependencies bootstrap
🍃 Generating Spring Boot project
Application run failed
io.github.wimdeblauwe.ttcli.maven.MavenInitServiceException: java.io.IOException: Cannot run program "mvn" (in directory "./demo"): error=2, No such file or directory
	at io.github.wimdeblauwe.ttcli.maven.MavenInitService.generate(MavenInitService.java:20)
	at io.github.wimdeblauwe.ttcli.ProjectInitializationService.initialize(ProjectInitializationService.java:67)
	at io.github.wimdeblauwe.ttcli.Init.init(Init.java:70)
	at java.base@23.0.1/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
	at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
	at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:230)
	at org.springframework.shell.Shell.evaluate(Shell.java:248)
	at org.springframework.shell.Shell.run(Shell.java:159)
	at org.springframework.shell.jline.NonInteractiveShellRunner.run(NonInteractiveShellRunner.java:144)
	at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:66)
	at org.springframework.boot.SpringApplication.lambda$callRunner$4(SpringApplication.java:786)
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83)
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60)
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774)
	at java.base@23.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base@23.0.1/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base@23.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:571)
	at java.base@23.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base@23.0.1/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base@23.0.1/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base@23.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base@23.0.1/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:636)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at io.github.wimdeblauwe.ttcli.TamingThymeleafCliApplication.main(TamingThymeleafCliApplication.java:10)
	at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.io.IOException: Cannot run program "mvn" (in directory "./demo"): error=2, No such file or directory
	at java.base@23.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base@23.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at io.github.wimdeblauwe.ttcli.maven.MavenPomReaderWriter.formatPomDotXml(MavenPomReaderWriter.java:119)
	at io.github.wimdeblauwe.ttcli.maven.MavenPomReaderWriter.write(MavenPomReaderWriter.java:111)
	at io.github.wimdeblauwe.ttcli.maven.MavenInitService.addMavenDependencies(MavenInitService.java:41)
	at io.github.wimdeblauwe.ttcli.maven.MavenInitService.generate(MavenInitService.java:16)
	... 31 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base@23.0.1/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base@23.0.1/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
	at java.base@23.0.1/java.lang.ProcessImpl.start(ProcessImpl.java:225)
	at java.base@23.0.1/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 36 more

```

Although there is no `mvn` inside demo, it is available in PATH that I installed using `sdk`
Am I missing any steps?

**Comment by wimdeblauwe** [comment]
Hmm... I just did the same thing to test and it worked fine:

```
> ttcli version
1.5.1

> ttcli init
? Group:  com.example
? Artifact:  demo
? Project Name:  Demo
? Select Spring Boot version 3.3.4
? Select live reload implementation: dev-tools-based
? Web dependencies bootstrap
🍃 Generating Spring Boot project
✅ Done generating project at /Users/wdb/./demo

See HELP.md in the generated project for additional information.
```

When I run `mvn --version` from the same location, I get:

```
> mvn --version
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /Users/wdb/.sdkman/candidates/maven/current
Java version: 21.0.3, vendor: Eclipse Adoptium, runtime: /Users/wdb/.sdkman/candidates/java/21.0.3-tem
Default locale: en_BE, platform encoding: UTF-8
OS name: "mac os x", version: "14.6.1", arch: "x86_64", family: "mac"
```

Can you run `mvn --version` to see if that works?

**Comment by pmverma** [comment]
Thanks and apologies for bothering you with a trivial thing.
It seems I messed up my shell/env.

I installed the latest maven using `sdk install maven` and it is working fine now.
Let me close this ticket.

**Comment by wimdeblauwe** [comment]
No problem, glad you sorted it out.
