### ISSUE TITLE
Enable Windows build again

### ISSUE THREAD

**Issue by wimdeblauwe** [wimdeblauwe/ttcli#2]
Native builds currently fail on Windows with this error:

```
Error: Classes that should be initialized at run time got initialized during image building:
[2/7] Performing analysis...  [*]                                                                       (41.2s @ 0.81GB)
 org.slf4j.LoggerFactory was unintentionally initialized at build time. io.netty.channel.AbstractChannel caused initialization of this class with the following trace: 
   6,471 (72.61%) of  8,912 classes reachable
    at org.slf4j.LoggerFactory.<clinit>(LoggerFactory.java:89)
   8,255 (60.55%) of 13,633 fields reachable
    at io.netty.util.internal.logging.Slf4JLoggerFactory.<init>(Slf4JLoggerFactory.java:42)
  25,980 (44.23%) of 58,740 methods reachable
    at io.netty.util.internal.logging.Slf4JLoggerFactory$NopInstanceHolder.<clinit>(Slf4JLoggerFactory.java:63)
    at io.netty.util.internal.logging.Slf4JLoggerFactory.getInstanceWithNopCheck(Slf4JLoggerFactory.java:59)
    at io.netty.util.internal.logging.InternalLoggerFactory.useSlf4JLoggerFactory(InternalLoggerFactory.java:62)
    at io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(InternalLoggerFactory.java:42)
    at io.netty.util.internal.logging.InternalLoggerFactory.getDefaultFactory(InternalLoggerFactory.java:111)
    at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:134)
    at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:127)
    at io.netty.channel.AbstractChannel.<clinit>(AbstractChannel.java:45)
```

This is most likely due to https://github.com/graalvm/native-build-tools/issues/363 Need to retest once that one is fixed.

**Comment by wimdeblauwe** [comment]
Version 0.9.18 with bugfix released nows: https://graalvm.github.io/native-build-tools/latest/index.html#_release_0_9_18

**Comment by wimdeblauwe** [comment]
Windows build ok again.
